Assistant checkpoint: Fix syntax error in database_manager.py
Assistant generated file changes:
- resources/lib/database_manager.py: Fix syntax in insert_imdb_export method

---

User prompt:

now ```2025-02-04 15:17:43.566 T:17404   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: invalid syntax (database_manager.py, line 723)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\kcook\AppData\Roaming\Kodi\addons\plugin.video.librarygenie\main.py", line 2, in <module>
                                                       from resources.lib.addon_helper import run_addon  # Updated import
                                                     File "C:\Users\kcook\AppData\Roaming\Kodi\addons\plugin.video.librarygenie\resources\lib\addon_helper.py", line 6, in <module>
                                                       from resources.lib.database_manager import DatabaseManager
                                                     File "C:\Users\kcook\AppData\Roaming\Kodi\addons\plugin.video.librarygenie\resources\lib\database_manager.py", line 723
                                                       query = """
                                                               INSERT INTO imdb_exports
                                                               (kodi_id, imdb_id, title, year, filename, path)
                                                               VALUES (?, ?, ?, ?, ?, ?)
                                                           """        for movie in movies:
                                                                  ^
                                                   SyntaxError: invalid syntax
                                                   -->End of Python script error report<--
```