Assistant checkpoint: Add missing log_once function and fix config initialization
Assistant generated file changes:
- resources/lib/utils/utils.py: Add missing log_once function
- resources/lib/config/config_manager.py: Initialize _max_folder_depth attribute

---

User prompt:

```2025-08-22 01:43:53.860 T:8696    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ImportError'>
                                                   Error Contents: cannot import name 'log_once' from 'resources.lib.utils.utils' (C:\Users\kcook\AppData\Roaming\Kodi\addons\plugin.video.librarygenie\resources\lib\utils\utils.py)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\kcook\AppData\Roaming\Kodi\addons\plugin.video.librarygenie\service.py", line 6, in <module>
                                                       from resources.lib.config.config_manager import Config
                                                     File "C:\Users\kcook\AppData\Roaming\Kodi\addons\plugin.video.librarygenie\resources\lib\config\config_manager.py", line 6, in <module>
                                                       from resources.lib.utils.utils import log_once
                                                   ImportError: cannot import name 'log_once' from 'resources.lib.utils.utils' (C:\Users\kcook\AppData\Roaming\Kodi\addons\plugin.video.librarygenie\resources\lib\utils\utils.py)
                                                   -->End of Python script error report<--
```

Replit-Commit-Author: Assistant
Replit-Commit-Session-Id: 30aa37f8-52f7-4e5d-8ba0-6e6d53ddbc67