Assistant checkpoint: Fixed missing router import and main function
Assistant generated file changes:
- lib/addon.py: Remove router import and fix main function, Fix main function to use AddonController, Fix _diagnose_logging function import, Fix AddonController constructor parameter

---

User prompt:

fix ```2025-08-28 16:58:07.690 T:21996   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'lib.ui.router'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\kcook\kodi_port\Kodi\portable_data\addons\plugin.video.librarygenie\plugin.py", line 25, in <module>
                                                       from lib.addon import AddonController
                                                     File "C:\Users\kcook\kodi_port\Kodi\portable_data\addons\plugin.video.librarygenie\lib\addon.py", line 15, in <module>
                                                       from .ui.router import Router
                                                   ModuleNotFoundError: No module named 'lib.ui.router'
                                                   -->End of Python script error report<--```

Replit-Commit-Author: Assistant
Replit-Commit-Session-Id: b1a71ef7-8f01-4ce8-823c-0fbd8a05e9bb