Assistant checkpoint: Fix debug inspection functionality
Assistant generated file changes:
- resources/lib/addon_helper.py: Fix debug inspection code

---

User prompt:

Clicking debug context item produces no change in gui. logs show ```2025-02-05 19:56:46.219 T:26056   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'SyntaxError'>
                                                   Error Contents: invalid syntax (addon_helper.py, line 67)
                                                   Traceback (most recent call last):
                                                     File "C:\Users\kcook\AppData\Roaming\Kodi\addons\plugin.video.librarygenie\main.py", line 2, in <module>
                                                       from resources.lib.addon_helper import run_addon  # Updated import
                                                     File "C:\Users\kcook\AppData\Roaming\Kodi\addons\plugin.video.librarygenie\resources\lib\addon_helper.py", line 67
                                                       elif action == "debug_inspect":
                                                       ^
                                                   SyntaxError: invalid syntax
                                                   -->End of Python script error report<--
``` double check that this should open up a window and display 1 row of data from the table with movie details