Assistant checkpoint: Fix context menu module import path issue
Assistant generated file changes:
- resources/lib/context.py: Fix module import path for context menu execution

---

User prompt:

review issue, research code related to it and fix it ```2025-08-18 01:59:14.346 T:20988    info <general>: LibraryGenie [INFO]: Successfully called li.setInfo('video', info_dict)
2025-08-18 01:59:14.346 T:20988    info <general>: LibraryGenie [INFO]: === BUILDING URL ===
2025-08-18 01:59:14.347 T:20988    info <general>: LibraryGenie [INFO]: Added folder_id to URL params: 17
2025-08-18 01:59:14.347 T:20988    info <general>: LibraryGenie [INFO]: FOLDER_CONTEXT_DEBUG: Building options URL with params: {'action': 'show_options', 'view': 'folder', 'folder_id': 17}
2025-08-18 01:59:14.347 T:20988    info <general>: LibraryGenie [INFO]: FOLDER_CONTEXT_DEBUG: Built options URL: plugin://plugin.video.librarygenie/?action=show_options&view=folder&folder_id=17
2025-08-18 01:59:16.399 T:7500     info <general>: Loading skin file: DialogContextMenu.xml, load type: KEEP_IN_MEMORY
2025-08-18 01:59:19.628 T:26212   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ModuleNotFoundError'>
                                                   Error Contents: No module named 'resources'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\kcook\AppData\Roaming\Kodi\addons\plugin.video.librarygenie\resources\lib\context.py", line 3, in <module>
                                                       from resources.lib.core.context import run as _run  # rename to your callable if needed
                                                   ModuleNotFoundError: No module named 'resources'
                                                   -->End of Python script error report<--
                  ```

Replit-Commit-Author: Assistant
Replit-Commit-Session-Id: fcfadacb-e980-40f2-a15c-7b5a0ef7cceb